package com.iliadmastery.country_datasource.cache.model

import com.iliadmastery.country_domain.Country
import com.iliadmastery.countrydatasource.cache.Country_Entity

/**
 * Country_Entity is generated by SqlDelight.
 * Check /country-datasource/build/generated/sqldelight/code/Database/debug/
 */

/**
 * Mapping function that decode database model [Country_Entity] to model [Country]
 */
fun Country_Entity.toCountry(): Country {
    return Country(
        id = id,
        name = name,
        /**
         * Here it would have been possible to manage with an adapter as for CountryAssignedStatusEnum
         * being a very simple management, we avoid loading a new adapter in the DB
         * [com.iliadmastery.country_domain.CountryAssignedStatusEnum]
         */
        continents = continents.split(";"),
        languages = languages.split(";"),
        flag = flag,
        coatOfArms = coatOfArms,
        area = area,
        population = population,
        unMember = unmember,
        status = status,
    )
}