package com.iliadmastery.ui_countrylist.ui.test

/**
 * These constants are useful for performing isolation tests and screenshots on composed framework
 */

const val TAG_COUNTRY_SEARCH_BAR = "TAG_COUNTRY_SEARCH_BAR"
const val TAG_COUNTRY_NAME = "TAG_COUNTRY_NAME"
const val TAG_COUNTRY_FILTER_BTN = "TAG_COUNTRY_FILTER_BTN"
const val TAG_COUNTRY_FILTER_DIALOG = "TAG_COUNTRY_FILTER_DIALOG"
const val TAG_COUNTRY_FILTER_DIALOG_RESET = "TAG_COUNTRY_FILTER_DIALOG_RESET"
const val TAG_COUNTRY_FILTER_DIALOG_DONE = "TAG_COUNTRY_FILTER_DIALOG_DONE"
const val TAG_COUNTRY_FILTER_COUNTRY_CHECKBOX = "TAG_COUNTRY_FILTER_COUNTRY_CHECKBOX"
const val TAG_COUNTRY_FILTER_DESC = "TAG_COUNTRY_FILTER_DESC"
const val TAG_COUNTRY_FILTER_ASC = "TAG_COUNTRY_FILTER_ASC"
const val TAG_COUNTRY_FILTER_CONTINENT_RADIOBUTTON = "TAG_COUNTRY_FILTER_CONTINENT_RADIOBUTTON"
const val TAG_COUNTRY_FILTER_LANGUAGE_BUTTON = "TAG_COUNTRY_FILTER_LANGUAGE_BUTTON"
const val TAG_COUNTRY_FILTER_LANGUAGE_DROP_DOWN = "TAG_COUNTRY_FILTER_LANGUAGE_DROP_DOWN"
const val TAG_COUNTRY_FILTER_LANGUAGE_DROP_DOWN_ITEM = "TAG_COUNTRY_FILTER_LANGUAGE_DROP_DOWN_ITEM"
const val TAG_COUNTRY_CONTINENTS = "TAG_COUNTRY_CONTINENTS"
