package com.iliadmastery.ui_countrydetail.ui

import com.iliadmastery.core.domain.UIComponent

/**
 * Events generated by the Country Detail Screen ui
 *
 */
sealed class CountryDetailEvents{

    data class GetCountryFromCache(
        val id: Long,
    ): CountryDetailEvents()

    object OnRemoveHeadFromQueue: CountryDetailEvents()

    data class Error(
        val uiComponent: UIComponent
    ): CountryDetailEvents()
}
