package com.iliadmastery.ui_countrylist.ui

import com.iliadmastery.core.domain.UIComponent
import com.iliadmastery.core.domain.UIComponentState
import com.iliadmastery.country_domain.ContinentFilter
import com.iliadmastery.country_domain.CountryFilter
import com.iliadmastery.country_domain.LanguageFilter

/**
 * Events generated by the Country List Screen Ui
 *
 */
sealed class CountryListEvents{

    object GetCountries: CountryListEvents()

    object FilterCountries: CountryListEvents()

    data class UpdateCountryName(
        val countryName: String,
    ): CountryListEvents()

    data class UpdateCountryFilter(
        val countryFilter: CountryFilter
    ): CountryListEvents()

    data class UpdateContinentFilter(
        val continent: ContinentFilter
    ): CountryListEvents()

    data class UpdateLanguageFilter(
        val language: LanguageFilter
    ): CountryListEvents()

    data class UpdateFilterDialogState(
        val uiComponentState: UIComponentState
    ): CountryListEvents()

    object OnRemoveHeadFromQueue: CountryListEvents()

    data class Error(
        val uiComponent: UIComponent
    ): CountryListEvents()
}
